### ISSUE TITLE
Question:: BitHelper - sha3 vs keccak

### ISSUE THREAD

**Issue by dkataskin** [exthereum/blockchain#1]
Hello sirs, I looked into implementation of `BitHelper` and I see that `keccakf1600` is used. While the algorithm is the same `keccakf1600` package contains NIST `SHA3` implementation and it's different from original Keccak and Ethereum is using original Keccak.

Shouldn't `BitHelper` be utilizing keccak hash instead of sha3? SHA3 can be reversed to to Keccak by changing padding and there is a fork that does that for `keccakf1600`.

**Comment by hayesgm** [comment]
You're right that the current implementation does not look to match those tests as is, e.g.:

```elixir
iex> BitHelper.kec("teststring") |> :binary.decode_unsigned |> inspect(base: :hex)
0xA52EF463EDB03558BE0598FB9A3AE67E0FC41C44BD0B1D4392B354D1E817FEA8
```

**Comment by dkataskin** [comment]
I suggest doing the following: 

- fork `erlang-keccakf1600` under exthereum
- apply this change https://github.com/jur0/erlang-keccakf1600/commit/a87d31d32250091262e0da5ee2c2a4535bc50945
- modify `mix.exs` to pull keccak package from exthereum

**Comment by hayesgm** [comment]
FYI, right now we're using https://hex.pm/packages/keccakf1600_orig to solve this issue.

**Comment by dkataskin** [comment]
@hayesgm thank you, I guess the issue can be closed then.
